name = "Bigsimr"
uuid = "8782c2a4-92bb-4214-98d7-3150cbd7a677"
authors = ["Alex Knudson <alexk.706@gmail.com>"]
repo = "https://github.com/SchisslerGroup/Bigsimr.jl.git"
version = "0.8.7"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
HypergeometricFunctions = "34004b35-14d8-5ef3-9330-4cdb6864b03a"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
IntervalRootFinding = "d2bf35a9-74e0-55ec-b149-d360ff49b807"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
PDMats = "90014a1f-27ba-587c-ab20-58faa44d9150"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SharedArrays = "1a1011a3-84de-559e-8e89-a11a2f7dc383"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Distributions = "0.22, 0.23, 0.24, 0.25"
FastGaussQuadrature = "0.4"
HypergeometricFunctions = "0.2, 0.3"
IntervalArithmetic = "0.16, 0.17, 0.18, 0.19, 0.20"
IntervalRootFinding = "0.5"
IterTools = "1.3, 1.4"
LsqFit = "0.10, 0.12, 0.13"
PDMats = "0.10, 0.11"
Polynomials = "1, 2, 3"
QuadGK = "2.4, 2.6"
SpecialFunctions = "1, 2"
StatsBase = "0.32, 0.33"
julia = "1.6, 1.7, 1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
